export const userActionTypes = {
    SET_CURRENT_USER : 'SET_CURRENT_USER',
    GOOGLE_SIGN_IN_START : 'GOOGLE_SIGN_IN_START',
    GOOGLE_SIGN_IN_SUCCESS : 'GOOGLE_SIGN_IN_SUCCESS',
    GOOGLE_SIGN_IN_ERROR : 'GOOGLE_SIGN_IN_ERROR',
    EMAIL_SIGN_IN_START : 'EMAIL_SIGN_IN_START',
    EMAIL_SIGN_IN_SUCCESS : 'EMAIL_SIGN_IN_SUCCESS',
    EMAIL_SIGN_IN_ERROR : 'GOOGLE_SIGN_IN_ERROR'
}