const userActionTypes = {
    GOOGLE_SIGN_IN_START : 'GOOGLE_SIGN_IN_START',
    SIGN_IN_SUCCESS : 'SIGN_IN_SUCCESS',
    SIGN_IN_ERROR : 'SIGN_IN_ERROR',
    EMAIL_SIGN_IN_START : 'EMAIL_SIGN_IN_START',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION'

}

export default userActionTypes;